"""Audit CEM decision fidelity on OGBench Cube with true MuJoCo rollouts.

The ordinary world-model loss asks whether a fixed action sequence has a
small prediction error.  This audit asks the control-facing question instead:
given the *same* CEM population, does the learned cost rank and refit the
candidates in the same way as the simulator oracle?

For every paired dataset state and selected CEM round, the script:

1. records complete populations generated by each requested checkpoint;
2. scores every population with every requested checkpoint;
3. replays every candidate from the exact qpos/qvel start state in MuJoCo;
4. compares predicted and true top-k sets and their CEM update directions.

The first population is generated with common random numbers, so it is exactly
paired across generators.  Later populations expose path-dependent optimizer
feedback.  ``audit.max_candidates=-1`` is required for formal proposal and
top-k coverage claims; positive values are intended only for smoke tests.

Example:

  python scripts/plan/ogbench_candidate_fidelity.py \
      policy=/path/to/k1.pt \
      plan_config.horizon=10 plan_config.receding_horizon=10 \
      +plan_config.history_len=3 eval.goal_offset_steps=50 \
      +audit.generators=/path/to/k1.pt,/path/to/k5.pt \
      +audit.scorers=/path/to/k1.pt,/path/to/k5.pt \
      +audit.labels=K1,K5 +audit.num_states=8 \
      +audit.steps=0,4,9,19,29 +audit.max_candidates=-1 \
      +audit.sim_workers=4 \
      +audit.include_expert_anchors=true \
      +audit.init_prior=zero \
      '+audit.expert_noise_scales="0.02,0.05,0.1"' \
      +audit.min_initial_distance=0.04 \
      +audit.out=/tmp/ogbench_candidate_fidelity.npz
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from copy import deepcopy
import json
import os
from pathlib import Path
import time
import warnings

os.environ['MUJOCO_GL'] = 'egl'

import hydra
import gymnasium as gym
import numpy as np
from omegaconf import DictConfig, OmegaConf
import torch

import stable_worldmodel as swm
from stable_worldmodel.solver.callbacks import CEMPopulationRecorder
from stable_worldmodel.world.world import (
    _apply_callables,
    _extract_init_goal,
    _refresh_dataset_rendered_images,
    _seed_history_infos,
)

from candidate_oracle import make_process, prepare_model_info, score_candidates
from eval_wm import get_dataset, img_transform


warnings.filterwarnings(
    'ignore',
    message='.*Casting input x to numpy array.*',
    category=UserWarning,
    module='gymnasium.spaces.box',
)
warnings.filterwarnings(
    'ignore',
    message=".*Box (low|high)'s precision lowered.*",
    category=UserWarning,
    module='gymnasium.spaces.box',
)


def comma_list(value, *, name: str) -> list[str]:
    values = [item.strip() for item in str(value).split(',') if item.strip()]
    if not values:
        raise ValueError(f'{name} must contain at least one value')
    return values


def parse_steps(value, *, n_steps: int) -> list[int]:
    steps = sorted({int(item) for item in comma_list(value, name='audit.steps')})
    if steps[0] < 0 or steps[-1] >= n_steps:
        raise ValueError(f'audit.steps={steps} must be inside [0, {n_steps - 1}]')
    return steps


def sample_starts(
    dataset,
    *,
    num_states: int,
    goal_offset: int,
    min_initial_distance: float,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Sample evaluator-compatible rows, optionally excluding easy starts."""
    ep_col = 'episode_idx' if 'episode_idx' in dataset.column_names else 'ep_idx'
    episode_idx = np.asarray(dataset.get_col_data(ep_col))
    step_idx = np.asarray(dataset.get_col_data('step_idx'))
    episodes, inverse = np.unique(episode_idx, return_inverse=True)
    max_step = np.full(len(episodes), -1, dtype=np.int64)
    np.maximum.at(max_step, inverse, step_idx)
    valid = np.flatnonzero(step_idx <= max_step[inverse] - goal_offset)

    # Match eval_wm/candidate_oracle's historical off-by-one convention.
    eligible = valid[:-1]
    goal_rows = eligible + goal_offset
    contiguous = (
        (goal_rows < len(step_idx))
        & (episode_idx[goal_rows] == episode_idx[eligible])
        & (step_idx[goal_rows] == step_idx[eligible] + goal_offset)
    )
    if not np.all(contiguous):
        eligible = eligible[contiguous]
        goal_rows = goal_rows[contiguous]

    block_pos = np.asarray(dataset.get_col_data('privileged_block_0_pos'))
    initial_distance = np.linalg.norm(
        block_pos[eligible] - block_pos[goal_rows], axis=-1
    )
    if min_initial_distance > 0:
        keep = initial_distance > min_initial_distance
        eligible = eligible[keep]
        initial_distance = initial_distance[keep]

    if len(eligible) < num_states:
        raise ValueError(
            f'Only {len(eligible)} eligible starts, but audit.num_states={num_states}'
        )
    chosen = rng.choice(len(eligible), size=num_states, replace=False)
    # Sorting keeps state order stable and makes overlap audits easy to inspect.
    order = np.argsort(eligible[chosen])
    chosen = chosen[order]
    rows = eligible[chosen]
    return (
        rows.astype(np.int64),
        episode_idx[rows].astype(np.int64),
        step_idx[rows].astype(np.int64),
        initial_distance[chosen].astype(np.float64),
    )


def prepare_world_info(
    world,
    dataset,
    *,
    episode: int,
    start: int,
    goal_offset: int,
    callables,
    history_len: int,
    action_block: int,
) -> tuple[dict, dict[str, np.ndarray], dict[str, np.ndarray]]:
    """Reproduce dataset-seeded OGBench eval up to the first planner call."""
    init_state, goal_state, _ = _extract_init_goal(
        dataset, [int(episode)], [int(start)], int(goal_offset)
    )
    world.reset(seed=init_state.get('seed'), options=None)

    if callables:
        merged = {**init_state, **goal_state}
        env_init = {key: value[0] for key, value in merged.items()}
        _apply_callables(world.envs.envs[0].unwrapped, callables, env_init)

    shape_prefix = world.infos['pixels'].shape[:2]
    for source in (init_state, goal_state):
        for key, value in source.items():
            if key in ('pixels', 'goal'):
                continue
            if key in world.infos or key in goal_state:
                world.infos[key] = np.broadcast_to(
                    value[:, None, ...], shape_prefix + value.shape[1:]
                ).copy()

    history_frames = max(0, int(history_len) - 1)
    if history_frames:
        _seed_history_infos(
            world.envs.envs,
            world.infos,
            dataset,
            [int(episode)],
            [int(start)],
            history_frames,
            int(action_block),
        )

    _refresh_dataset_rendered_images(
        world.envs.envs, world.infos, init_state, goal_state
    )
    required_init = ('qpos', 'qvel', 'privileged_block_0_pos')
    required_goal = (
        'goal_privileged_block_0_pos',
        'goal_privileged_block_0_quat',
    )
    missing = [key for key in required_init if key not in init_state]
    missing += [key for key in required_goal if key not in goal_state]
    if missing:
        raise KeyError(f'OGBench dataset is missing required fields: {missing}')

    simulator_init = {
        'qpos': np.asarray(init_state['qpos'][0]).copy(),
        'qvel': np.asarray(init_state['qvel'][0]).copy(),
        'block_pos': np.asarray(init_state['privileged_block_0_pos'][0]).copy(),
    }
    simulator_goal = {
        'block_pos': np.asarray(
            goal_state['goal_privileged_block_0_pos'][0]
        ).copy(),
        'block_quat': np.asarray(
            goal_state['goal_privileged_block_0_quat'][0]
        ).copy(),
    }
    return deepcopy(world.infos), simulator_init, simulator_goal


def build_expert_anchors(
    dataset,
    *,
    episode: int,
    start: int,
    horizon: int,
    action_block: int,
    action_scaler,
    noise_scales: list[float],
    noise_per_scale: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, list[str]]:
    """Build expert-continuation support plus local normalized perturbations.

    Offline datasets differ on whether ``action[t]`` enters or leaves state
    ``t``.  Keep both exact alignments; their true replays make the convention
    explicit instead of silently assuming one.  Noise is centered on the
    usual next-row convention, where the reset row has a NaN action.
    """
    num_actions = int(horizon) * int(action_block)
    chunk = dataset.load_chunk(
        np.asarray([int(episode)]),
        np.asarray([int(start)]),
        np.asarray([int(start) + num_actions + 1]),
    )[0]
    raw = np.asarray(chunk['action'], dtype=np.float32)
    if len(raw) < num_actions + 1:
        raise ValueError(
            f'Expert anchor needs {num_actions + 1} rows, got {len(raw)}'
        )

    raw_next = np.nan_to_num(raw[1 : num_actions + 1])
    raw_same = np.nan_to_num(raw[:num_actions])
    normalized_next = action_scaler.transform(raw_next).astype(np.float32)
    normalized_same = action_scaler.transform(raw_same).astype(np.float32)
    action_dim = normalized_next.shape[-1]
    shape = (int(horizon), int(action_block) * action_dim)
    anchors = [normalized_next.reshape(shape), normalized_same.reshape(shape)]
    names = ['expert_next', 'expert_same']

    for scale in noise_scales:
        if scale < 0:
            raise ValueError('audit.expert_noise_scales must be non-negative')
        for noise_i in range(int(noise_per_scale)):
            noisy = normalized_next + rng.normal(
                loc=0.0,
                scale=float(scale),
                size=normalized_next.shape,
            ).astype(np.float32)
            anchors.append(noisy.reshape(shape))
            names.append(f'expert_next_noise_{scale:g}_{noise_i:02d}')
    return np.stack(anchors), names


def selected_indices(
    recorded_cost: np.ndarray,
    *,
    max_candidates: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Retain all candidates formally, or a broad subset for smoke tests."""
    n = len(recorded_cost)
    if max_candidates <= 0 or max_candidates >= n:
        return np.arange(n, dtype=np.int64)

    order = np.argsort(recorded_cost, kind='stable')
    group = max(1, max_candidates // 3)
    proposed = [
        *order[:group],
        *order[np.linspace(0, n - 1, group, dtype=np.int64)],
        *rng.permutation(n),
        *order,
    ]
    chosen: list[int] = []
    seen: set[int] = set()
    for raw_index in proposed:
        index = int(raw_index)
        if index in seen:
            continue
        chosen.append(index)
        seen.add(index)
        if len(chosen) == max_candidates:
            break
    return np.asarray(chosen, dtype=np.int64)


def execute_candidate(
    raw,
    *,
    initial_state: dict[str, np.ndarray],
    goal_state: dict[str, np.ndarray],
    candidate: np.ndarray,
    action_scaler,
    action_block: int,
    seed: int,
) -> dict[str, object]:
    """Replay one normalized open-loop sequence without rendering pixels."""
    raw.reset(seed=int(seed))
    raw.set_target_pos(
        cube_id=0,
        target_pos=goal_state['block_pos'],
        target_quat=goal_state['block_quat'],
    )
    raw.set_state(initial_state['qpos'], initial_state['qvel'])

    # ``ManipSpaceEnv.action_space`` constructs a new Box on every access.
    # Its raw control limits are already fixed at five dimensions, so use the
    # cached arrays and avoid thousands of Box allocations and warnings.
    action_dim = int(np.asarray(raw.action_low).shape[-1])
    expected = int(action_block) * action_dim
    if candidate.shape[-1] != expected:
        raise ValueError(
            f'Candidate dim {candidate.shape[-1]} != '
            f'action_block*action_dim {expected}'
        )
    normalized = np.asarray(candidate, dtype=np.float32).reshape(-1, action_dim)
    actions = action_scaler.inverse_transform(normalized).astype(
        np.float32, copy=False
    )
    roundtrip = action_scaler.transform(actions)
    roundtrip_error = float(np.max(np.abs(roundtrip - normalized)))

    ever_success = False
    for action in actions:
        _, _, terminated, truncated, info = raw.step(action)
        ever_success |= bool(info.get('success', False))
        if terminated or truncated:
            break

    terminal_pos = np.asarray(
        raw._data.joint('object_joint_0').qpos[:3]
    ).copy()
    distance = float(np.linalg.norm(terminal_pos - goal_state['block_pos']))
    success = bool(ever_success or distance <= 0.04)
    terminal_state = np.concatenate(
        [np.asarray(raw._data.qpos), np.asarray(raw._data.qvel)]
    ).copy()
    return {
        'distance': distance,
        'success': success,
        'terminal_pos': terminal_pos,
        'terminal_state': terminal_state,
        'roundtrip_error': roundtrip_error,
    }


class SimulatorPool:
    """Replay independent candidates concurrently in cloned MuJoCo envs."""

    def __init__(self, template_raw, world_cfg, *, workers: int) -> None:
        self.workers = max(1, int(workers))
        self.raws = [template_raw]
        self.handles = []
        world_kwargs = OmegaConf.to_container(world_cfg, resolve=True)
        env_name = world_kwargs.pop('env_name')
        world_kwargs.pop('num_envs', None)
        max_episode_steps = world_kwargs.pop('max_episode_steps')
        for _ in range(self.workers - 1):
            handle = gym.make(
                env_name,
                max_episode_steps=max_episode_steps,
                **world_kwargs,
            )
            self.handles.append(handle)
            self.raws.append(handle.unwrapped)
        self.executor = (
            ThreadPoolExecutor(max_workers=self.workers)
            if self.workers > 1
            else None
        )

    @staticmethod
    def _execute_chunk(raw, items, kwargs):
        return [
            (
                key,
                execute_candidate(
                    raw,
                    candidate=candidate.astype(np.float32),
                    **kwargs,
                ),
            )
            for key, candidate in items
        ]

    def execute(
        self,
        *,
        candidates: np.ndarray,
        initial_state: dict[str, np.ndarray],
        goal_state: dict[str, np.ndarray],
        action_scaler,
        action_block: int,
        seed: int,
        cache: dict[bytes, dict[str, object]],
    ) -> dict[str, np.ndarray]:
        keys = []
        missing: dict[bytes, np.ndarray] = {}
        for candidate in candidates:
            contiguous = np.ascontiguousarray(candidate, dtype=np.float16)
            key = contiguous.tobytes()
            keys.append(key)
            if key not in cache:
                missing.setdefault(key, contiguous)

        if missing:
            items = list(missing.items())
            kwargs = {
                'initial_state': initial_state,
                'goal_state': goal_state,
                'action_scaler': action_scaler,
                'action_block': action_block,
                'seed': seed,
            }
            chunks = [items[i :: self.workers] for i in range(self.workers)]
            if self.executor is None:
                completed = [self._execute_chunk(self.raws[0], chunks[0], kwargs)]
            else:
                futures = [
                    self.executor.submit(
                        self._execute_chunk, raw, chunk, kwargs
                    )
                    for raw, chunk in zip(self.raws, chunks, strict=True)
                    if chunk
                ]
                completed = [future.result() for future in futures]
            for chunk in completed:
                cache.update(chunk)

        results = [cache[key] for key in keys]
        return {
            'distance': np.asarray([item['distance'] for item in results]),
            'success': np.asarray(
                [item['success'] for item in results], dtype=bool
            ),
            'terminal_pos': np.stack(
                [item['terminal_pos'] for item in results]
            ),
            'roundtrip_error': np.asarray(
                [item['roundtrip_error'] for item in results]
            ),
        }

    def close(self) -> None:
        if self.executor is not None:
            self.executor.shutdown(wait=True)
        for handle in self.handles:
            handle.close()


def cosine(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=np.float64).reshape(-1)
    b = np.asarray(b, dtype=np.float64).reshape(-1)
    denom = float(np.linalg.norm(a) * np.linalg.norm(b))
    if denom <= 1e-12:
        return float('nan')
    return float(np.dot(a, b) / denom)


def rank_metrics(
    predicted: np.ndarray,
    true: np.ndarray,
    *,
    topk: int,
) -> dict[str, float]:
    from scipy.stats import kendalltau, spearmanr

    predicted = np.asarray(predicted)
    true = np.asarray(true)
    k = min(int(topk), len(true))
    pred_top = np.argsort(predicted, kind='stable')[:k]
    true_top = np.argsort(true, kind='stable')[:k]
    overlap = len(np.intersect1d(pred_top, true_top)) / k
    best = float(np.min(true))
    span = float(np.max(true) - best)
    regret = float(true[int(np.argmin(predicted))] - best)
    return {
        'spearman': float(spearmanr(predicted, true).statistic),
        'kendall': float(kendalltau(predicted, true).statistic),
        'topk_overlap': float(overlap),
        'regret': regret,
        'normalized_regret': 0.0 if span <= 0 else regret / span,
    }


def summarize(
    *,
    labels: list[str],
    generators: list[str],
    steps: list[int],
    pred: np.ndarray,
    true: np.ndarray,
    success: np.ndarray,
    refit_true: np.ndarray,
    refit_success: np.ndarray,
    update_cosine: np.ndarray,
    topk: int,
) -> None:
    # Shapes: state, generator, round, scorer, candidate; true lacks scorer.
    for generator_i, generator in enumerate(generators):
        print(f'\nGENERATOR {Path(generator).parent.name or Path(generator).name}')
        for round_i, step in enumerate(steps):
            fields = [
                f'step={step:02d}',
                f'oracle_min={np.mean(np.min(true[:, generator_i, round_i], axis=1)):.4f}',
                'coverage='
                f'{np.mean(np.any(success[:, generator_i, round_i], axis=1)):.3f}',
            ]
            for scorer_i, label in enumerate(labels):
                metrics = [
                    rank_metrics(
                        pred[state_i, generator_i, round_i, scorer_i],
                        true[state_i, generator_i, round_i],
                        topk=topk,
                    )
                    for state_i in range(len(true))
                ]
                fields.append(
                    f'{label}:rho={np.nanmean([m["spearman"] for m in metrics]):.3f},'
                    f'top{topk}={np.mean([m["topk_overlap"] for m in metrics]):.3f},'
                    f'refit={np.mean(refit_true[:, generator_i, round_i, scorer_i]):.4f}/'
                    f'{np.mean(refit_success[:, generator_i, round_i, scorer_i]):.3f},'
                    f'ucos={np.nanmean(update_cosine[:, generator_i, round_i, scorer_i]):.3f}'
                )
            print(' '.join(fields))


@hydra.main(version_base=None, config_path='./config', config_name='cube')
def run(cfg: DictConfig) -> None:
    audit = cfg.get('audit', {})
    generators = comma_list(
        audit.get('generators', str(cfg.policy)), name='audit.generators'
    )
    scorers = comma_list(
        audit.get('scorers', ','.join(generators)), name='audit.scorers'
    )
    labels = comma_list(
        audit.get('labels', ','.join(Path(name).parent.name for name in scorers)),
        name='audit.labels',
    )
    if len(labels) != len(scorers):
        raise ValueError('audit.labels must have the same length as audit.scorers')
    all_models = list(dict.fromkeys([*generators, *scorers]))
    num_states = int(audit.get('num_states', 8))
    max_candidates = int(audit.get('max_candidates', -1))
    sim_workers = int(audit.get('sim_workers', 4))
    min_initial_distance = float(audit.get('min_initial_distance', 0.04))
    include_expert_anchors = bool(audit.get('include_expert_anchors', False))
    init_prior = str(audit.get('init_prior', 'zero'))
    if init_prior not in {'zero', 'expert_next'}:
        raise ValueError(
            "audit.init_prior must be one of {'zero', 'expert_next'}"
        )
    if init_prior == 'expert_next' and not include_expert_anchors:
        raise ValueError(
            'audit.init_prior=expert_next requires '
            'audit.include_expert_anchors=true'
        )
    noise_scales = [
        float(value)
        for value in comma_list(
            audit.get('expert_noise_scales', '0.02,0.05,0.1'),
            name='audit.expert_noise_scales',
        )
    ]
    noise_per_scale = int(audit.get('expert_noise_per_scale', 10))
    output_path = Path(
        str(audit.get('out', 'outputs/ogbench_candidate_fidelity.npz'))
    )

    cfg.eval.num_eval = 1
    cfg.world.max_episode_steps = (
        int(cfg.plan_config.horizon) * int(cfg.plan_config.action_block) + 5
    )
    world = swm.World(**cfg.world, image_shape=(224, 224))
    dataset = get_dataset(cfg, cfg.eval.dataset_name)
    process = make_process(dataset, cfg.dataset.keys_to_cache)
    image_dtype = torch.bfloat16 if bool(cfg.get('bf16', False)) else torch.float32
    transform = {
        'pixels': img_transform(cfg, image_dtype),
        'pixels_hist': img_transform(cfg, image_dtype),
        'goal': img_transform(cfg, image_dtype),
    }
    plan_config = swm.PlanConfig(**cfg.plan_config)

    print(f'Loading audit models: {all_models}')
    models = {}
    for model_name in all_models:
        model = swm.wm.utils.load_pretrained(model_name)
        if bool(cfg.get('bf16', False)):
            model = model.to(torch.bfloat16)
        model = model.to('cuda').eval()
        model.requires_grad_(False)
        model.interpolate_pos_encoding = True
        models[model_name] = model

    solvers = {}
    recorders = {}
    steps = None
    for generator_name in generators:
        solver = hydra.utils.instantiate(cfg.solver, model=models[generator_name])
        generator_steps = parse_steps(
            audit.get('steps', '0,4,9,19,29'), n_steps=solver.n_steps
        )
        if steps is None:
            steps = generator_steps
        elif steps != generator_steps:
            raise RuntimeError('All generators must use the same CEM steps')
        recorder = CEMPopulationRecorder(steps)
        solver.callbacks.append(recorder)
        solvers[generator_name] = solver
        recorders[generator_name] = recorder
    assert steps is not None

    template_policy = swm.policy.WorldModelPolicy(
        solver=solvers[generators[0]],
        config=plan_config,
        process=process,
        transform=transform,
    )
    world.set_policy(template_policy)
    for generator_name in generators[1:]:
        solvers[generator_name].configure(
            action_space=world.envs.action_space,
            n_envs=1,
            config=plan_config,
        )

    rng = np.random.default_rng(int(cfg.seed))
    rows, episodes, starts, sampled_initial_distance = sample_starts(
        dataset,
        num_states=num_states,
        goal_offset=int(cfg.eval.goal_offset_steps),
        min_initial_distance=min_initial_distance,
        rng=rng,
    )
    callables = cfg.eval.get('callables')
    if callables is not None:
        callables = OmegaConf.to_container(callables, resolve=True)

    all_candidates = []
    all_candidate_indices = []
    all_pred = []
    all_true = []
    all_success = []
    all_terminal_pos = []
    all_prev_mean = []
    all_recorded_mean = []
    all_recorded_mean_true = []
    all_recorded_mean_success = []
    all_refit_mean = []
    all_oracle_refit_mean = []
    all_refit_true = []
    all_refit_success = []
    all_oracle_refit_true = []
    all_oracle_refit_success = []
    all_update_cosine = []
    all_update_norm_ratio = []
    initial_qpos = []
    initial_qvel = []
    initial_block_pos = []
    goal_block_pos = []
    goal_block_quat = []
    roundtrip_errors: list[float] = []
    reset_errors: list[float] = []
    anchor_names: list[str] = []
    started = time.time()

    raw = world.envs.envs[0].unwrapped
    simulator = SimulatorPool(raw, cfg.world, workers=sim_workers)
    try:
        for state_i, (episode, start) in enumerate(
            zip(episodes, starts, strict=True)
        ):
            info, simulator_init, simulator_goal = prepare_world_info(
                world,
                dataset,
                episode=int(episode),
                start=int(start),
                goal_offset=int(cfg.eval.goal_offset_steps),
                callables=callables,
                history_len=int(cfg.plan_config.history_len),
                action_block=int(cfg.plan_config.action_block),
            )
            model_info = prepare_model_info(template_policy, info)
            initial_qpos.append(simulator_init['qpos'])
            initial_qvel.append(simulator_init['qvel'])
            initial_block_pos.append(simulator_init['block_pos'])
            goal_block_pos.append(simulator_goal['block_pos'])
            goal_block_quat.append(simulator_goal['block_quat'])
            state_cache: dict[bytes, dict[str, object]] = {}
            if include_expert_anchors:
                expert_anchors, state_anchor_names = build_expert_anchors(
                    dataset,
                    episode=int(episode),
                    start=int(start),
                    horizon=int(cfg.plan_config.horizon),
                    action_block=int(cfg.plan_config.action_block),
                    action_scaler=process['action'],
                    noise_scales=noise_scales,
                    noise_per_scale=noise_per_scale,
                    rng=np.random.default_rng(
                        int(cfg.seed) * 1_000_000 + state_i
                    ),
                )
                if not anchor_names:
                    anchor_names = state_anchor_names
                elif anchor_names != state_anchor_names:
                    raise RuntimeError('Expert anchor names changed across states')
                anchor_indices = -np.arange(
                    1, len(expert_anchors) + 1, dtype=np.int64
                )
            else:
                expert_anchors = np.empty(
                    (
                        0,
                        int(cfg.plan_config.horizon),
                        int(cfg.plan_config.action_block) * 5,
                    ),
                    dtype=np.float32,
                )
                anchor_indices = np.empty(0, dtype=np.int64)

            state_candidates = []
            state_candidate_indices = []
            state_pred = []
            state_true = []
            state_success = []
            state_terminal_pos = []
            state_prev_mean = []
            state_recorded_mean = []
            state_recorded_mean_true = []
            state_recorded_mean_success = []
            state_refit_mean = []
            state_oracle_refit_mean = []
            state_refit_true = []
            state_refit_success = []
            state_oracle_refit_true = []
            state_oracle_refit_success = []
            state_update_cosine = []
            state_update_norm_ratio = []

            for generator_i, generator_name in enumerate(generators):
                solver = solvers[generator_name]
                # Same seed makes round zero exactly paired across generators.
                solver.torch_gen.manual_seed(int(cfg.seed) * 100_000 + state_i)
                init_action = None
                if init_prior == 'expert_next':
                    # Hidden-oracle support intervention: initialize CEM at the
                    # dataset's exact future continuation while keeping the
                    # population size, random noise, rounds, and WM calls
                    # unchanged. This is a causal diagnostic, not a deployable
                    # policy result.
                    init_action = torch.from_numpy(
                        expert_anchors[0:1].astype(np.float32, copy=False)
                    )
                solver(deepcopy(model_info), init_action=init_action)
                trace = recorders[generator_name].history[-1]
                if [record['step'] for record in trace] != steps:
                    raise RuntimeError(
                        f'{generator_name}: trace steps do not match {steps}'
                    )

                generator_candidates = []
                generator_candidate_indices = []
                generator_pred = []
                generator_true = []
                generator_success = []
                generator_terminal_pos = []
                generator_prev_mean = []
                generator_recorded_mean = []
                generator_recorded_mean_true = []
                generator_recorded_mean_success = []
                generator_refit_mean = []
                generator_oracle_refit_mean = []
                generator_refit_true = []
                generator_refit_success = []
                generator_oracle_refit_true = []
                generator_oracle_refit_success = []
                generator_update_cosine = []
                generator_update_norm_ratio = []

                for record in trace:
                    population = record['candidates'][0].float().numpy()
                    recorded_cost = record['costs'][0].numpy()
                    indices = selected_indices(
                        recorded_cost,
                        max_candidates=max_candidates,
                        rng=rng,
                    )
                    candidates = population[indices]
                    candidate_indices = indices
                    if len(expert_anchors):
                        candidates = np.concatenate(
                            [candidates, expert_anchors], axis=0
                        )
                        candidate_indices = np.concatenate(
                            [candidate_indices, anchor_indices]
                        )
                    predicted = np.stack(
                        [
                            score_candidates(models[name], model_info, candidates)
                            for name in scorers
                        ]
                    )
                    execution = simulator.execute(
                        candidates=candidates,
                        initial_state=simulator_init,
                        goal_state=simulator_goal,
                        action_scaler=process['action'],
                        action_block=int(cfg.plan_config.action_block),
                        seed=int(cfg.seed) + state_i,
                        cache=state_cache,
                    )
                    true_distance = execution['distance']
                    k = min(int(solver.topk), len(candidates))
                    prev_mean = record['prev_mean'][0].float().numpy()
                    oracle_elite = np.argsort(true_distance, kind='stable')[:k]
                    oracle_refit_mean = candidates[oracle_elite].mean(axis=0)
                    scorer_refit_means = []
                    scorer_update_cosines = []
                    scorer_update_norm_ratios = []
                    for scorer_i in range(len(scorers)):
                        elite = np.argsort(
                            predicted[scorer_i], kind='stable'
                        )[:k]
                        refit_mean = candidates[elite].mean(axis=0)
                        scorer_refit_means.append(refit_mean)
                        pred_delta = refit_mean - prev_mean
                        oracle_delta = oracle_refit_mean - prev_mean
                        scorer_update_cosines.append(
                            cosine(pred_delta, oracle_delta)
                        )
                        oracle_norm = float(np.linalg.norm(oracle_delta))
                        scorer_update_norm_ratios.append(
                            float(np.linalg.norm(pred_delta)) / oracle_norm
                            if oracle_norm > 1e-12
                            else float('nan')
                        )
                    scorer_refit_means = np.stack(scorer_refit_means)
                    refit_execution = simulator.execute(
                        candidates=scorer_refit_means,
                        initial_state=simulator_init,
                        goal_state=simulator_goal,
                        action_scaler=process['action'],
                        action_block=int(cfg.plan_config.action_block),
                        seed=int(cfg.seed) + state_i,
                        cache=state_cache,
                    )
                    oracle_refit_execution = simulator.execute(
                        candidates=oracle_refit_mean[None],
                        initial_state=simulator_init,
                        goal_state=simulator_goal,
                        action_scaler=process['action'],
                        action_block=int(cfg.plan_config.action_block),
                        seed=int(cfg.seed) + state_i,
                        cache=state_cache,
                    )
                    recorded_mean_value = record['mean'][0].float().numpy()
                    recorded_mean_execution = simulator.execute(
                        candidates=recorded_mean_value[None],
                        initial_state=simulator_init,
                        goal_state=simulator_goal,
                        action_scaler=process['action'],
                        action_block=int(cfg.plan_config.action_block),
                        seed=int(cfg.seed) + state_i,
                        cache=state_cache,
                    )

                    generator_candidates.append(
                        candidates.astype(np.float16, copy=False)
                    )
                    generator_candidate_indices.append(candidate_indices)
                    generator_pred.append(predicted)
                    generator_true.append(true_distance)
                    generator_success.append(execution['success'])
                    generator_terminal_pos.append(execution['terminal_pos'])
                    generator_prev_mean.append(prev_mean)
                    generator_recorded_mean.append(recorded_mean_value)
                    generator_recorded_mean_true.append(
                        recorded_mean_execution['distance'][0]
                    )
                    generator_recorded_mean_success.append(
                        recorded_mean_execution['success'][0]
                    )
                    generator_refit_mean.append(scorer_refit_means)
                    generator_oracle_refit_mean.append(oracle_refit_mean)
                    generator_refit_true.append(refit_execution['distance'])
                    generator_refit_success.append(refit_execution['success'])
                    generator_oracle_refit_true.append(
                        oracle_refit_execution['distance'][0]
                    )
                    generator_oracle_refit_success.append(
                        oracle_refit_execution['success'][0]
                    )
                    generator_update_cosine.append(scorer_update_cosines)
                    generator_update_norm_ratio.append(
                        scorer_update_norm_ratios
                    )
                    roundtrip_errors.extend(execution['roundtrip_error'].tolist())

                    metrics = [
                        rank_metrics(
                            predicted[scorer_i],
                            true_distance,
                            topk=k,
                        )
                        for scorer_i in range(len(scorers))
                    ]
                    print(
                        f'[{state_i + 1}/{num_states}] '
                        f'generator={generator_i + 1}/{len(generators)} '
                        f'step={record["step"]:02d} n={len(candidates)} '
                        f'oracle={true_distance.min():.4f} '
                        f'coverage={int(execution["success"].any())} '
                        + ' '.join(
                            f'{labels[i]}:rho={metrics[i]["spearman"]:.3f},'
                            f'top{k}={metrics[i]["topk_overlap"]:.3f},'
                            f'refit={refit_execution["distance"][i]:.4f}'
                            for i in range(len(scorers))
                        )
                        + f' actual={recorded_mean_execution["distance"][0]:.4f}/'
                        f'{int(recorded_mean_execution["success"][0])}'
                        + f' elapsed={(time.time() - started) / 60:.1f}m'
                    )

                    if state_i == 0 and generator_i == 0 and record['step'] == steps[0]:
                        repeat = execute_candidate(
                            raw,
                            initial_state=simulator_init,
                            goal_state=simulator_goal,
                            candidate=candidates[0],
                            action_scaler=process['action'],
                            action_block=int(cfg.plan_config.action_block),
                            seed=int(cfg.seed) + state_i,
                        )
                        reset_errors.append(
                            float(
                                np.max(
                                    np.abs(
                                        repeat['terminal_pos']
                                        - execution['terminal_pos'][0]
                                    )
                                )
                            )
                        )

                state_candidates.append(np.stack(generator_candidates))
                state_candidate_indices.append(
                    np.stack(generator_candidate_indices)
                )
                state_pred.append(np.stack(generator_pred))
                state_true.append(np.stack(generator_true))
                state_success.append(np.stack(generator_success))
                state_terminal_pos.append(np.stack(generator_terminal_pos))
                state_prev_mean.append(np.stack(generator_prev_mean))
                state_recorded_mean.append(np.stack(generator_recorded_mean))
                state_recorded_mean_true.append(
                    np.asarray(generator_recorded_mean_true)
                )
                state_recorded_mean_success.append(
                    np.asarray(generator_recorded_mean_success)
                )
                state_refit_mean.append(np.stack(generator_refit_mean))
                state_oracle_refit_mean.append(
                    np.stack(generator_oracle_refit_mean)
                )
                state_refit_true.append(np.stack(generator_refit_true))
                state_refit_success.append(np.stack(generator_refit_success))
                state_oracle_refit_true.append(
                    np.asarray(generator_oracle_refit_true)
                )
                state_oracle_refit_success.append(
                    np.asarray(generator_oracle_refit_success)
                )
                state_update_cosine.append(
                    np.asarray(generator_update_cosine)
                )
                state_update_norm_ratio.append(
                    np.asarray(generator_update_norm_ratio)
                )

            all_candidates.append(np.stack(state_candidates))
            all_candidate_indices.append(np.stack(state_candidate_indices))
            all_pred.append(np.stack(state_pred))
            all_true.append(np.stack(state_true))
            all_success.append(np.stack(state_success))
            all_terminal_pos.append(np.stack(state_terminal_pos))
            all_prev_mean.append(np.stack(state_prev_mean))
            all_recorded_mean.append(np.stack(state_recorded_mean))
            all_recorded_mean_true.append(
                np.stack(state_recorded_mean_true)
            )
            all_recorded_mean_success.append(
                np.stack(state_recorded_mean_success)
            )
            all_refit_mean.append(np.stack(state_refit_mean))
            all_oracle_refit_mean.append(np.stack(state_oracle_refit_mean))
            all_refit_true.append(np.stack(state_refit_true))
            all_refit_success.append(np.stack(state_refit_success))
            all_oracle_refit_true.append(np.stack(state_oracle_refit_true))
            all_oracle_refit_success.append(
                np.stack(state_oracle_refit_success)
            )
            all_update_cosine.append(np.stack(state_update_cosine))
            all_update_norm_ratio.append(np.stack(state_update_norm_ratio))
    finally:
        simulator.close()
        world.close()

    candidates = np.stack(all_candidates)
    candidate_indices = np.stack(all_candidate_indices)
    pred = np.stack(all_pred)
    true = np.stack(all_true)
    success = np.stack(all_success)
    terminal_pos = np.stack(all_terminal_pos)
    prev_mean = np.stack(all_prev_mean)
    recorded_mean = np.stack(all_recorded_mean)
    recorded_mean_true = np.stack(all_recorded_mean_true)
    recorded_mean_success = np.stack(all_recorded_mean_success)
    refit_mean = np.stack(all_refit_mean)
    oracle_refit_mean = np.stack(all_oracle_refit_mean)
    refit_true = np.stack(all_refit_true)
    refit_success = np.stack(all_refit_success)
    oracle_refit_true = np.stack(all_oracle_refit_true)
    oracle_refit_success = np.stack(all_oracle_refit_success)
    update_cosine = np.stack(all_update_cosine)
    update_norm_ratio = np.stack(all_update_norm_ratio)

    metadata = {
        'version': 1,
        'formal_full_population': bool(
            max_candidates <= 0 or max_candidates >= int(cfg.solver.num_samples)
        ),
        'min_initial_distance': min_initial_distance,
        'success_threshold': 0.04,
        'common_random_first_population': True,
        'sim_workers': sim_workers,
        'include_expert_anchors': include_expert_anchors,
        'init_prior': init_prior,
        'expert_noise_scales': noise_scales,
        'expert_noise_per_scale': noise_per_scale,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_path,
        version=np.asarray(1),
        metadata=np.asarray(json.dumps(metadata, sort_keys=True)),
        generators=np.asarray(generators),
        scorers=np.asarray(scorers),
        labels=np.asarray(labels),
        anchor_names=np.asarray(anchor_names),
        steps=np.asarray(steps),
        rows=rows,
        episodes=episodes,
        starts=starts,
        sampled_initial_distance=sampled_initial_distance,
        initial_qpos=np.stack(initial_qpos),
        initial_qvel=np.stack(initial_qvel),
        initial_block_pos=np.stack(initial_block_pos),
        goal_block_pos=np.stack(goal_block_pos),
        goal_block_quat=np.stack(goal_block_quat),
        horizon=np.asarray(int(cfg.plan_config.horizon)),
        goal_offset=np.asarray(int(cfg.eval.goal_offset_steps)),
        action_block=np.asarray(int(cfg.plan_config.action_block)),
        topk=np.asarray(int(solvers[generators[0]].topk)),
        candidates=candidates,
        candidate_indices=candidate_indices,
        pred=pred,
        true=true,
        success=success,
        terminal_pos=terminal_pos,
        prev_mean=prev_mean,
        recorded_mean=recorded_mean,
        recorded_mean_true=recorded_mean_true,
        recorded_mean_success=recorded_mean_success,
        refit_mean=refit_mean,
        oracle_refit_mean=oracle_refit_mean,
        refit_true=refit_true,
        refit_success=refit_success,
        oracle_refit_true=oracle_refit_true,
        oracle_refit_success=oracle_refit_success,
        update_cosine=update_cosine,
        update_norm_ratio=update_norm_ratio,
        max_roundtrip_error=np.asarray(max(roundtrip_errors, default=float('nan'))),
        max_reset_error=np.asarray(max(reset_errors, default=float('nan'))),
        elapsed_seconds=np.asarray(time.time() - started),
    )

    summarize(
        labels=labels,
        generators=generators,
        steps=steps,
        pred=pred,
        true=true,
        success=success,
        refit_true=refit_true,
        refit_success=refit_success,
        update_cosine=update_cosine,
        topk=int(solvers[generators[0]].topk),
    )
    print(f'\nresults -> {output_path}')
    print(
        f'shapes candidates={candidates.shape} pred={pred.shape} true={true.shape}'
    )
    print(
        f'max_reset_error={max(reset_errors, default=float("nan")):.3e} '
        f'max_roundtrip_error={max(roundtrip_errors, default=float("nan")):.3e}'
    )
    print(f'elapsed={(time.time() - started) / 60:.1f} minutes')


if __name__ == '__main__':
    run()
