"""Multi-proposer CEM with post-search rank-consensus selection."""

from __future__ import annotations

import time
from typing import Any

import torch

from .callbacks import CEMArchiveRecorder
from .cross_validated_cem import score_action_candidates


class CEMPortfolioSolver:
    """Combine smooth CEM iterates generated by different world models.

    Every proposer runs an ordinary, independent CEM search. The resulting
    updated means are pooled only after all adaptive searches finish, then all
    world models rank the common pool. Averaging fractional ranks avoids
    assuming that latent-distance scales are calibrated across checkpoints.
    """

    def __init__(
        self,
        *,
        solvers: list,
        models: list,
        names: list[str],
        steps: list[int] | tuple[int, ...] | set[int],
        scorer_batch_size: int = 1,
    ) -> None:
        if len(solvers) < 2:
            raise ValueError('a CEM portfolio needs at least two solvers')
        if len(models) != len(solvers) or len(names) != len(solvers):
            raise ValueError('solvers, models, and names must have equal size')
        if len(set(names)) != len(names):
            raise ValueError('portfolio names must be unique')
        if scorer_batch_size < 1:
            raise ValueError('scorer_batch_size must be positive')

        requested_steps = tuple(sorted({int(step) for step in steps}))
        if not requested_steps or requested_steps[0] < 0:
            raise ValueError('steps must contain non-negative CEM iterations')

        self.solvers = list(solvers)
        self.models = list(models)
        self.names = tuple(names)
        self.steps = requested_steps
        self.scorer_batch_size = int(scorer_batch_size)
        self.recorders = []
        self.selection_history: list[dict[str, torch.Tensor]] = []

        for solver in self.solvers:
            if not hasattr(solver, 'callbacks'):
                raise TypeError('every portfolio solver needs callbacks')
            n_steps = getattr(solver, 'n_steps', None)
            if n_steps is not None and requested_steps[-1] >= int(n_steps):
                raise ValueError(
                    f'archive step {requested_steps[-1]} is outside '
                    f'a solver with {n_steps} iterations'
                )
            recorder = CEMArchiveRecorder(requested_steps)
            solver.callbacks.append(recorder)
            self.recorders.append(recorder)

    @property
    def n_envs(self) -> int:
        return self.solvers[0].n_envs

    @property
    def action_dim(self) -> int:
        return self.solvers[0].action_dim

    @property
    def horizon(self) -> int:
        return self.solvers[0].horizon

    def configure(self, **kwargs: Any) -> None:
        for solver in self.solvers:
            solver.configure(**kwargs)

    def __call__(self, *args: Any, **kwargs: Any) -> dict:
        return self.solve(*args, **kwargs)

    @staticmethod
    def _archive_means(
        recorder: CEMArchiveRecorder,
        expected_steps: tuple[int, ...],
    ) -> torch.Tensor:
        batches = []
        for batch_i, trace in enumerate(recorder.history):
            actual = tuple(int(entry['step']) for entry in trace)
            if actual != expected_steps:
                raise RuntimeError(
                    f'archive batch {batch_i} has steps {actual}, '
                    f'expected {expected_steps}'
                )
            batches.append(
                torch.stack(
                    [entry['mean'] for entry in trace],
                    dim=1,
                )
            )
        if not batches:
            raise RuntimeError('portfolio CEM archive is empty')
        return torch.cat(batches)

    @staticmethod
    def _fractional_ranks(values: torch.Tensor) -> torch.Tensor:
        n_values = values.shape[-1]
        if n_values == 1:
            return torch.zeros_like(values)
        order = torch.argsort(values, dim=-1, stable=True)
        ranks = torch.argsort(order, dim=-1, stable=True)
        return ranks.float() / (n_values - 1)

    def selection_summary(self) -> dict:
        if not self.selection_history:
            return {
                'num_plans': 0,
                'proposer_counts': {},
                'step_counts': {},
            }
        proposer = torch.cat(
            [entry['selected_proposer'] for entry in self.selection_history]
        )
        steps = torch.cat(
            [entry['selected_step'] for entry in self.selection_history]
        )
        proposer_unique, proposer_counts = torch.unique(
            proposer,
            return_counts=True,
        )
        step_unique, step_counts = torch.unique(steps, return_counts=True)
        return {
            'num_plans': int(len(proposer)),
            'proposer_counts': {
                self.names[int(index)]: int(count)
                for index, count in zip(
                    proposer_unique,
                    proposer_counts,
                    strict=True,
                )
            },
            'step_counts': {
                int(step): int(count)
                for step, count in zip(
                    step_unique,
                    step_counts,
                    strict=True,
                )
            },
        }

    @torch.inference_mode()
    def solve(
        self,
        info_dict: dict,
        init_action: torch.Tensor | None = None,
    ) -> dict:
        started = time.time()
        solver_outputs = [
            solver(info_dict, init_action=init_action)
            for solver in self.solvers
        ]
        proposer_candidates = [
            self._archive_means(recorder, self.steps)
            for recorder in self.recorders
        ]
        candidates = torch.cat(proposer_candidates, dim=1)
        scorer_costs = torch.stack(
            [
                score_action_candidates(
                    model,
                    info_dict,
                    candidates,
                    env_batch_size=self.scorer_batch_size,
                )
                for model in self.models
            ],
            dim=1,
        )
        consensus = self._fractional_ranks(scorer_costs).mean(dim=1)
        selected = consensus.argmin(dim=1)
        batch = torch.arange(len(selected))

        candidate_proposer = torch.arange(
            len(self.solvers),
            dtype=torch.int64,
        ).repeat_interleave(len(self.steps))
        candidate_steps = torch.as_tensor(
            self.steps,
            dtype=torch.int64,
        ).repeat(len(self.solvers))
        selected_proposer = candidate_proposer[selected]
        selected_step = candidate_steps[selected]

        outputs = solver_outputs[0]
        outputs['actions'] = candidates[batch, selected]
        self.selection_history.append(
            {
                'selected_index': selected.clone(),
                'selected_proposer': selected_proposer.clone(),
                'selected_step': selected_step.clone(),
            }
        )
        outputs['portfolio'] = {
            'names': self.names,
            'steps': candidate_steps,
            'proposers': candidate_proposer,
            'scorer_costs': scorer_costs,
            'consensus': consensus,
            'selected_index': selected,
            'selected_proposer': selected_proposer,
            'selected_step': selected_step,
            'candidates': candidates,
            'elapsed_seconds': time.time() - started,
        }
        return outputs
